void main{
    
    nomevariavelUm: integer;
    nomevariavelDois, nomevariavelTres : char;
    nomevariavelQuatro : integer; nomevariavelCinco : string;
    i: integer;
    
    inicio

    if(i >= i){
        ;
    }else{
        ;
    };

    if(i >= i){
        ;
    };

    while(a < b){
	    ;
    };

    do{
        ;
    }while(i == i);

    for (i = 0; i < 10; ++1){
        cout << "A menor que B";
    };

fim
}