void main{
    
    nomevariavelUm: integer;
    nomevariavelDois, nomevariavelTres : char;
    nomevariavelQuatro : integer; nomevariavelCinco : string;
    i: integer;

    float soma(float a; float b){
	    return(1 + 1);
    }
    
    inicio

    if(i >= i){
        ;
    }else{
        ;
    };

    while(a < b){
	    ;
    };

    do{
        ;
    }while(i == i);

    for (i = 0; i < 10; ++1){
        ;
    };

fim
}